### ISSUE TITLE
[QUESTION][IDEA] Enhancement on events making PR move

### ISSUE THREAD

**Issue by mmornati** [alex-page/move-assigned-pulls-column#5]
## Why? 
The project is actually taking care of a PR project move when the PR assignment changes. As the automatic events on GitHub projects are actually limited, what about the extensions of this action to support other events?

I was thinking to create an action to move a PR from "Needs Review" (moved here automatically when a review is asked) to "Test Ready" when the PR is merged on the master branch (as it is also automatically deployed by our CI/CD system).

## How?
I just have a quick view of the `index.js` file, so I will say something completely wrong and to challenge, but, anyway:

* the action should accept args (like for example [this action](https://github.com/marketplace/actions/github-action-for-filtering-on-event-payloads) does).
* the arg will be the event to take care about: merged.on, assigned, ...
* the index, based on the arguments, will execute the required checks to know if the PR should be moved on the project boards

What do you think about it? Is it something you can accept on this action or do you prefer to keep it for a single "event"?

I will for sure take care of the necessary code and propose a PR 😄

**Comment by alex-page** [comment]
Hey @mmornati sorry for the late reply. I have done this by creating a new project:
https://github.com/alex-page/github-project-automation-plus
